### PR TITLE
Improved: Z-index for dropdowns(#536)

### LINKED ISSUE #536: Increase z-index for Dropdown
## Current behavior

Dropdown hides with bottom navigation

## Expected behavior

Dropdown should not get hide with the bottom navigation

## Steps to reproduce the issue

Open any dropdwon in mobile view

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by AishwaryShrivastav**
### Related Issues

Closes #536 

### Short Description and Why It's Useful

Used SFUI's variable '--select-dropdown-z-index' to set the value to 2.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by Fifciu — CHANGES_REQUESTED** [review]
Please update changelog

**Comment by Fifciu** [comment]
Please update changelog & resolve conflicts

**Comment by AishwaryShrivastav** [comment]
Added change logs in #573

**Comment by AishwaryShrivastav** [comment]
@Fifciu we can merge this improvement also in our next release.

**Review by Fifciu — APPROVED** [review]

**Pull request merged**
