### PR TITLE
Removed: Unnecessary font overridden of titles for category navbar(#488)

### LINKED ISSUE #488: Font override for titles on category page Navbar
## Current behavior

Unnecessary font of titles are overridden 

## Expected behavior

SFUI default font style will make heading consistent 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by AishwaryShrivastav**
### Related Issues

Closes #488 

### Short Description and Why It's Useful

Removing the font override will make it consistent.

### Screenshots of Visual Changes before/after (If There Are Any)

Before

before

After

after

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by AishwaryShrivastav** [comment]
Thanks @dt2patel suggesting this improvement

**Comment by AishwaryShrivastav** [comment]
We have removed the font override here and now the headings matches with the [Figma](https://www.figma.com/community/file/883240116671776403).

**Review by Fifciu — CHANGES_REQUESTED** [review]
Great, please update changelog

**Comment by Fifciu** [comment]
Nothing to merge after a rebase

**Pull request closed without merging**
