### PR TITLE
Improved: Hover effect of Filter icon on category page (#486)

### LINKED ISSUE #486: Filter's icon color on category page
## Current behavior

Its overridden with hardcoded values  

## Expected behavior

Instead of hardcoded values we can use sfui color variables 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by AishwaryShrivastav**
Fixed the fill on hover and removed hard coded color from filter icon.

### Related Issues

Closes #486 

### Short Description and Why It's Useful

Improves the hover colour changing 

### Screenshots of Visual Changes before/after (If There Are Any)

Before

before

After

after

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with the description of your change

### Contribution and Currently Important Rules Acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by AishwaryShrivastav** [comment]
Thanks @dt2patel for suggesting these changes!!

**Comment by AishwaryShrivastav** [comment]
If provided, I can also update the icon of filters, as per the figma

**Comment by AishwaryShrivastav** [comment]
On hover, the icon color will also modify, which was not modifying previously.

**Review by Fifciu — CHANGES_REQUESTED** [review]
Great but changelog please

**Comment by Fifciu** [comment]
Please update changelog

**Comment by AishwaryShrivastav** [comment]
@Fifciu Please close this PR for now

**Pull request closed without merging**
