### PR TITLE
Removed: Unnecessary code around product carousal on home page (#471-Extra-padding-carousal)

### LINKED ISSUE #471: Shrinked Carousals on Home Page
## Current behavior

There is a lot of padding on product carousal on home page.
This make it look thinner or shrinked 

## Expected behavior

Product carousals should have consitent view around the website, and we can remove the extra over ridden padding.

## Steps to reproduce the issue

Goto capybara.storefrontcloud.io/
Scroll down to product carousal

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details

- Browser:  All
- OS:  All
- Code Version:

### PR DESCRIPTION
**Pull request by AishwaryShrivastav**
Removed the padding from carousal in home page

### Related Issues

Closes #471 

### Short Description and Why It's Useful

Product carousals should have consistent spacing and visuals across the website, on home page is had a lot of padding which made it look thinner. 
Removed the over ridden padding.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by AishwaryShrivastav** [comment]
Many thanks to @dt2patel for suggesting these changes !!

**Comment by AishwaryShrivastav** [comment]
Here is a video where we've explained the changes for this improvement 

https://youtu.be/dPEIp80FBw0?t=585

**Comment by Fifciu** [comment]
Could you test this thing also locally? As I see on develop - nothing changes :/ . Probably it is similar situation to the earlier one

**Comment by dt2patel** [comment]
There isn't any expected change here, we're just deleting some extra code here that wasn't doing anything.

**Review by Fifciu — APPROVED** [review]
Ok got it

**Review by Fifciu — CHANGES_REQUESTED** [review]
Great job. Please update changelog

**Review by Fifciu — APPROVED** [review]

**Pull request merged**
