### PR TITLE
Updated: the code to render the images properly when using the mergeConfigurableChildren to false (#551)

### LINKED ISSUE #551: Images not rendering properly when setting the mergeConfigurableChildren to false
## Current behavior
Sometimes all the images are displayed on the same slide and when changing the image then blank slides are displayed.

## Expected behavior
Each image should be displayed on a single slide in the product gallery

## Steps to reproduce the issue

1. Set the mergeConfigurableChildren to false
2. Merge this MR to get unique images: https://github.com/DivanteLtd/vue-storefront/pull/5094
3. Go to ay product and then change the color

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

Related PR: https://github.com/DivanteLtd/vue-storefront/pull/5094

### PR DESCRIPTION
**Pull request by ymaheshwari1**
### Related Issues
#551 

Closes #551 

### Short Description and Why It's Useful
This will help in rendering the images as expected when setting the mergeConfigruableChildren to false.
Using another SfGallery for mergeconfigruableChildren as to re-render the gallery using the key value which is set to currentIndex.

### Screenshots of Visual Changes before/after (If There Are Any)
Before: 
image

After:
image

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ymaheshwari1** [comment]
Many thanks to @dt2patel for the suggestion, which help in solving the issue with very little change.

**Comment by Fifciu** [comment]
What would happen if `gallery.length` does not change between colors?

**Comment by ymaheshwari1** [comment]
> What would happen if `gallery.length` does not change between colors?

When gallery length is not changing then there is no issue in the product gallery, the gallery renders completely fine, the issue comes whenever the gallery length changes between either the product or when changing color.

**Review by Fifciu — CHANGES_REQUESTED** [review]
Ok, then please update changelog and we can merge it

**Comment by ymaheshwari1** [comment]
@Fifciu, I updated the PR, please have a look.

**Comment by ymaheshwari1** [comment]
Maintained the changelog for the PR here: https://github.com/vuestorefront/vsf-capybara/pull/573

**Review by Fifciu — APPROVED** [review]

**Pull request merged**
