### PR TITLE
Improved: the error message for the zip-code field on shipping and payment page(#589)

### LINKED ISSUE #589: Error messages are not displayed as per the field
## Current behavior
On the shipping and payment page the error messages are not as per the fields.

## Steps to reproduce the issue
1. Go to the shipping page
2. For the zip code field you will see the error message for the name field.

## Can you handle fixing this bug by yourself?
- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by ymaheshwari1**
### Related Issues
#589 

Closes #589 

### Short Description and Why It's Useful

Updated the error message for the zip code field on the shipping and payment page

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by AishwaryShrivastav — APPROVED** [review]
Change looks perfect, Please update the change log as they have a conflict in them

**Comment by ymaheshwari1** [comment]
> Change looks perfect, Please update the change log as they have a conflict in them

Resolved the conflicts in the changelog.

**Comment by AishwaryShrivastav** [comment]
@Fifciu these changes look good to me, we can merge these as well

**Review by Fifciu — APPROVED** [review]
Looks very well, thanks!

**Comment by dt2patel** [comment]
@ymaheshwari1 please resolve conflicts. I will merge this.

**Pull request merged**
