### PR TITLE
Memory increases after each page reload. 

### PR DESCRIPTION
**Pull request by one1note**
## Current behavior

Memory is never released and thus memory usage keeps increasing after each page reload.
In the default VSF theme the template imports are tagged with webpackChunkName and thus dynamically imported, in the Capybara theme however the imports are missing the webpackChunkName comment, which seems to cause the memory leak.

## Expected behavior

GC reclaims unused memory.

## Steps to reproduce the issue

1. Install the latest VSF with the Capybara theme in Docker.
2. Run, configure and import the demo data set
3. Run 'docker stats'
4. Browse to your vsf instance and keep reloading the page.
5. You should see the memory usage of your vsf container increase with each reload.

## Can you handle fixing this bug by yourself?

- [X ] YES
- [ ] NO

## Environment details

- Browser: Firefox 78.0.2 (64-bits)
- OS: Windows 10 pro 2006
- Code Version: latest Master (1.0.3)

### CODE REVIEW

**Comment by pkarw** [comment]
Moreover - if we stick to `static` loading the modules we need to remove the `MinimalLayout` at all - I mean it's just making the bundle bigger and actually none of the other modules is using it

**Review by RakowskiPrzemyslaw — APPROVED** [review]

**Review by AishwaryShrivastav — APPROVED** [review]
These changes looks good.

**Comment by AishwaryShrivastav** [comment]
@one1note Can you please update the change log

**Comment by one1note** [comment]
@AishwaryShrivastav I already added the change description in the change log...

**Pull request merged**
