### PR TITLE
Added: Active state for the profile in bottom navigation (#541)

### LINKED ISSUE #541: Active state of elements of bottom navigation
## Current behavior

Few elements from the bottom navigation don't have active state on clicking.

## Expected behavior

On clicking any of the items in bottom navigation, those itesm should have active state

## Steps to reproduce the issue

1. open https://capybara.storefrontcloud.io/ on mobile device
2. Click on profile in bottom navigation

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details

- Browser:  All
- OS:  All
- Code Version:  All

### PR DESCRIPTION
**Pull request by AishwaryShrivastav**
### Related Issues

Closes #541 

### Short Description and Why It's Useful

Added case for the profile in o-bottom-navigation.vue

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by dt2patel** [comment]
I wonder if we can update the code comment at line 66 which mentions that profile doesn't need active icon since its in the bottom nav. We can remove 'profile' from it and just leave 'cart'. What do you think @Fifciu

**Comment by AishwaryShrivastav** [comment]
We can also update the 'profile' icon to 'account' icon, which is used in the desktop header, to make icons consistent 
@dt2patel @Fifciu

**Comment by Fifciu** [comment]
It could be a good idea @AishwaryShrivastav

**Review by Fifciu — CHANGES_REQUESTED** [review]
Please update changelog & icon as you said

**Comment by AishwaryShrivastav** [comment]
Added new issue for icon and updated the changelog!

**Review by Fifciu — APPROVED** [review]

**Pull request merged**
