### PR TITLE
Improved: Placing of elements inside navbar main using grid(#467-Category-Navbar-Grid)

### LINKED ISSUE #467: Improvements in styling of category navbar for mobile and desktop view
## Current behavior

Mobile view of category navbar is broken 

## Expected behavior

Using grid can have better results on both mobile and desktop

## Steps to reproduce the issue

Open capybara.storefrontcloud.io/
Navigate to category

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser:  All
- OS:  All
- Code Version:

### PR DESCRIPTION
**Pull request by AishwaryShrivastav**
Instead of using flex, we used grid to organize the elements and their postioning and spacing, on both mobile and desktop.

### Related Issues

Closes #467 

### Short Description and Why It's Useful

Mobile view of category navbar was broken and we can have improved results on using grid instead of flexbox with less css code.

### Screenshots of Visual Changes before/after (If There Are Any)

No visual changes 

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by AishwaryShrivastav** [comment]
Many thanks to @dt2patel for suggesting these changes !!

**Comment by AishwaryShrivastav** [comment]
For any reference, here is a link of a video, where we're explaining the changes and why using grid instead of flex is more appropriate here. 

Here is the link to, the part of video where we are explaining the changes we made for this fix

https://youtu.be/dPEIp80FBw0?t=242

**Review by Fifciu — COMMENTED** [review]
I am not sure about this fix. Menu does not look to be broken in the current `develop`:
image

After applying your code for category.vue it looks like:
image

It looks differently but I would not call it a fix. Probably, you had different base branch than current `develop`. Could you please check it?

**Comment by dt2patel** [comment]
Hi @Fifciu,

You're right that the current Navbar is not broken, we were solving this on an older release (I think closer to the one that the current capybara demo site is on) where the spacing issues on mobile were more prevalent. The develop version of the Navbar doesn't seem to have those same problems, which it seemed to largely fix by using margin auto on the count element for mobile and no showing what sorting method is being used in the actual Navbar, on mobile at least. So it would make sense if you felt that this doesn't count as a fix.

I think however we can now look at this from an improvement standpoint. Using CSS grid yields a few advantages still, the usage of Grid Gap, having different layouts for mobile and desktop and a bonus centering trick of CSS Grid.

1. Using grid gap allows us to space elements without using margin or padding. In the future if someone were to choose to more filtering elements to the Navbar, they would not have to add their own padding between elements. Instead they will be able to leverage automatic spacing between elements through CSS Grid Gap.

2. Thought this can be done with Flexbox, customizing layouts between mobile and desktop using CSS Grid Areas is arguable both easier and more powerful. This also helps readability for new comers to our code since they don't have to identify the original order of the elements and how they have been reordered using Flexbox, instead the simple plain English method of Grid Areas is easier to understand and more user friendly.

3. This is a small one, but still kind of neat. By using margin auto on our count element, the count element is center between the right and left elements. This means that if either one grows or shrinks in size, the position of the count is affected. CSS Column templates avoids this (I won't go into detail here) and in the end yields a more app-like experience. You'll find similar UI patterns in iOS apps that have centered headers.

So that is my mini Ted Talk on CSS Grid :) . I am open to discussing it further and also understand if you feel that we don't need this. Either way, I feel CSS Grid will yield a more robust layout in the longterm and the browser support is also pretty much the same as Flexbox so I am confident our users wont run into any issues. 

Anyway, let me know what you think @Fifciu and @AishwaryShrivastav

**Comment by Fifciu** [comment]
I agree with your arguments. However, I cannot merge it as it is. Could you modify it to look like it does currently on develop? Then, the whole PR wouldn't be a real visual change - However, it would still be a big improvement as it would change flex to a more user-friendly grid. What do you think about it?

**Comment by AishwaryShrivastav** [comment]
As per our discussion, I have removed all visual changes and only the layout change from flex to grid exists.

**Review by Fifciu — CHANGES_REQUESTED** [review]
Great. Please resolve conflicts in changelog and we can merge it

**Review by Fifciu — APPROVED** [review]

**Pull request merged**
