### PR TITLE
Added: Safe Area of Elements in the Bottom Elements(#499)

### LINKED ISSUE #499: Add Webkit Safe Area in Capybara
## What is the motivation for adding/enhancing this feature?

Apple’s iPhone X has a screen that covers the entire face of the phone, save for a “notch” to make space for a camera and other various components. The result is some awkward situations for screen design, like constraining websites to a “safe area” and having white bars on the edges.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [X] YES
- [ ] NO

## Additional information

As per the discussion on [Slack](https://vuestorefront.slack.com/archives/C7G188MFZ/p1600020426125400)

### PR DESCRIPTION
**Pull request by AishwaryShrivastav**
### Related Issues

Closes #499 

### Short Description and Why It's Useful

Added Safe area padding on cookie notification, offline badge and bottom navigation

### Screenshots of Visual Changes before/after (If There Are Any)

[Video](https://youtu.be/ONhjsUDgeQE?t=585) sharing visuals changes for this Improvement

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [X] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by AishwaryShrivastav** [comment]
Currently only the bottom Elements in the Capybara need to have safe area, I have added them in Cookie notification, Bottom navigation and Offline Badge.
Many thanks to @dt2patel for the suggestion.

**Comment by AishwaryShrivastav** [comment]
Here is a tome coded [video](https://youtu.be/ONhjsUDgeQE?t=317) where we discussed this implementation

**Comment by AishwaryShrivastav** [comment]
Also added safe area padding for dropdowns.

**Review by Fifciu — APPROVED** [review]

**Review by Fifciu — CHANGES_REQUESTED** [review]
Please update changelog

**Comment by AishwaryShrivastav** [comment]
Added change logs in https://github.com/vuestorefront/vsf-capybara/pull/573

**Comment by AishwaryShrivastav** [comment]
Hey @Fifciu Please have a look at these changes, they looks good to me, we can merge them in the next release

**Review by Fifciu — APPROVED** [review]

**Pull request merged**
